openapi: 3.0.0
info:
  title: Health Care Auth Service API
  version: 1.0.0
  description: API xác thực cho hệ thống y tế (Patient, Doctor, Nurse, Admin, Pharmacist, Insurance, Lab Technician)
servers:
  - url: http://localhost:8000/api/
paths:
  /users/:
    post:
      summary: Đăng ký tài khoản mới
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Lỗi dữ liệu
  /users/login/:
    post:
      summary: Đăng nhập
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  refresh:
                    type: string
                  access:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Sai thông tin đăng nhập
  /users/me/:
    get:
      summary: Lấy thông tin user hiện tại
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Chưa xác thực
  /users/logout/:
    post:
      summary: Đăng xuất (thu hồi refresh token)
      tags: [Auth]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '205':
          description: Đăng xuất thành công
        '400':
          description: Lỗi
  /token/refresh/:
    post:
      summary: Refresh access token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '200':
          description: Token mới
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
        '401':
          description: Token không hợp lệ

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegister:
      type: object
      required: [email, username, password, role]
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [PATIENT, DOCTOR, NURSE, ADMIN, PHARMACIST, INSURANCE, LAB_TECHNICIAN]
        phone:
          type: string
        profile:
          $ref: '#/components/schemas/UserProfile'
    Login:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        username:
          type: string
        role:
          type: string
        phone:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        profile:
          $ref: '#/components/schemas/UserProfile'
    UserProfile:
      type: object
      properties:
        date_of_birth:
          type: string
          format: date
        address:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        postal_code:
          type: string
        specialization:
          type: string
        license_number:
          type: string
        insurance_provider:
          type: string
        insurance_number:
          type: string