# Generated by Django 5.0.2 on 2025-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_record_id", models.IntegerField()),
                ("medicine_id", models.IntegerField()),
                ("medicine_name", models.CharField(max_length=255)),
                ("medicine_description", models.TextField()),
                (
                    "medicine_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("medicine_manufacturer", models.CharField(max_length=255)),
                ("medicine_expiry_date", models.DateField()),
                ("quantity", models.IntegerField()),
                ("dosage", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
