# Generated by Django 5.0.2 on 2025-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="patient_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
