# Generated by Django 5.0.2 on 2025-05-27 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Tên")),
                ("last_name", models.CharField(max_length=100, verbose_name="Họ")),
                ("date_of_birth", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Số CMND/CCCD"
                    ),
                ),
                ("address", models.TextField(verbose_name="Địa chỉ")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Nhóm máu",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tiền sử bệnh"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Dị ứng"),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày đăng ký"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bệnh nhân",
                "verbose_name_plural": "Bệnh nhân",
                "ordering": ["-created_at"],
            },
        ),
    ]
