# Generated by Django 5.0.2 on 2025-05-27 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examination_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày khám"
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Chẩn đoán")),
                ("prescription", models.TextField(verbose_name="Đơn thuốc")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "doctor",
                    models.CharField(max_length=100, verbose_name="Bác sĩ điều trị"),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="Khoa phòng"),
                ),
                (
                    "treatment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ điều trị"),
                            ("IN_PROGRESS", "Đang điều trị"),
                            ("COMPLETED", "Đã hoàn thành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái điều trị",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bệnh án",
                "verbose_name_plural": "Hồ sơ bệnh án",
                "ordering": ["-examination_date"],
            },
        ),
    ]
