# Generated by Django 5.0.2 on 2025-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_medicalrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id_number",
            field=models.CharField(max_length=20, verbose_name="Số CMND/CCCD"),
        ),
    ]
